import { Film } from '@/types/film';

export const data: Film[] = [
    {
        id: '1',
        title: 'Film 1',
        status: 'available',
        description: 'Description 1',
        length: '100',
        release_year: '2006',
        category: 'action',
    },
    {
        id: '2',
        title: 'Film 2',
        status: 'unavailable',
        description: 'Description 2',
        length: '100',
        release_year: '2018',
        category: 'action',
    },
    {
        id: '3',
        title: 'Film 3',
        status: 'available',
        description: 'Description 3',
        length: '100',
        release_year: '2021',
        category: 'comedy',
    },
    {
        id: '4',
        title: 'Film 4',
        status: 'unavailable',
        description: 'Description 4',
        length: '100',
        release_year: '2019',
        category: 'action',
    },
    {
        id: '5',
        title: 'Film 5',
        status: 'available',
        description: 'Description 5',
        length: '100',
        release_year: '2003',
        category: 'action',
    },
    {
        id: '6',
        title: 'Film 6',
        status: 'unavailable',
        description: 'Description 6',
        length: '100',
        release_year: '2004',
        category: 'comedy',
    },
    {
        id: '7',
        title: 'Film 7',
        status: 'available',
        description: 'Description 7',
        length: '100',
        release_year: '2021',
        category: 'action',
    },
    {
        id: '8',
        title: 'Film 8',
        status: 'unavailable',
        description: 'Description 8',
        length: '100',
        release_year: '2005',
        category: 'comedy',
    },
    {
        id: '9',
        title: 'Film 9',
        status: 'available',
        description: 'Description 9',
        length: '100',
        release_year: '2014',
        category: 'action',
    },
    {
        id: '10',
        title: 'Film 10',
        status: 'unavailable',
        description: 'Description 10',
        length: '100',
        release_year: '2011',
        category: 'comedy',
    },
    {
        id: '11',
        title: 'Film 11',
        status: 'available',
        description: 'Description 11',
        length: '100',
        release_year: '2020',
        category: 'action',
    },
];
